export const indianStates = [
    {
      id: '1',
      name: 'Goa',
      image: 'https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Portuguese-influenced coastal culture with vibrant nightlife',
      festivals: 'Carnival, Shigmo, Christmas',
      famousPlaces: 'Baga Beach, Fort Aguada, Dudhsagar Falls',
      touristAttractions: [
        { name: 'Baga Beach', description: 'Popular beach with water sports' },
        { name: 'Fort Aguada', description: 'Historic Portuguese fort' },
        { name: 'Dudhsagar Falls', description: 'Majestic four-tiered waterfall' },
        { name: 'Basilica of Bom Jesus', description: 'UNESCO World Heritage Site' },
      ],
      budget: '₹15,000 - ₹30,000 per person for 3-4 days',
      bestTime: 'November to February',
      restaurants: [
        { name: 'Thalassa', cuisine: 'Greek', rating: 4.5 },
        { name: 'Brittos', cuisine: 'Seafood', rating: 4.3 },
        { name: 'Fisherman\'s Wharf', cuisine: 'Goan', rating: 4.4 },
      ],
      coordinates: { latitude: 15.2993, longitude: 74.1240 },
    },
    {
      id: '2',
      name: 'Kerala',
      image: 'https://images.pexels.com/photos/3452356/pexels-photo-3452356.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Rich cultural heritage with classical arts and backwaters',
      festivals: 'Onam, Vishu, Thrissur Pooram',
      famousPlaces: 'Munnar, Alleppey Backwaters, Kovalam Beach',
      touristAttractions: [
        { name: 'Munnar Tea Gardens', description: 'Scenic hill station with tea plantations' },
        { name: 'Alleppey Backwaters', description: 'Houseboat cruises through backwaters' },
        { name: 'Kovalam Beach', description: 'Beautiful crescent-shaped beach' },
        { name: 'Periyar Wildlife Sanctuary', description: 'Elephant and tiger reserve' },
      ],
      budget: '₹20,000 - ₹40,000 per person for 5-6 days',
      bestTime: 'October to March',
      restaurants: [
        { name: 'Dhe Puttu', cuisine: 'Kerala Traditional', rating: 4.6 },
        { name: 'Kayees Rahmathulla Hotel', cuisine: 'Biryani', rating: 4.5 },
        { name: 'Paragon Restaurant', cuisine: 'Seafood', rating: 4.4 },
      ],
      coordinates: { latitude: 10.8505, longitude: 76.2711 },
    },
    {
      id: '3',
      name: 'Rajasthan',
      image: 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Royal heritage with magnificent forts and palaces',
      festivals: 'Pushkar Fair, Desert Festival, Teej',
      famousPlaces: 'Jaipur, Udaipur, Jaisalmer',
      touristAttractions: [
        { name: 'Amber Fort', description: 'Majestic hilltop fort in Jaipur' },
        { name: 'City Palace Udaipur', description: 'Royal palace on Lake Pichola' },
        { name: 'Jaisalmer Fort', description: 'Living fort in the desert' },
        { name: 'Hawa Mahal', description: 'Iconic Palace of Winds' },
      ],
      budget: '₹25,000 - ₹50,000 per person for 7 days',
      bestTime: 'October to March',
      restaurants: [
        { name: 'Chokhi Dhani', cuisine: 'Rajasthani', rating: 4.5 },
        { name: 'Laxmi Mishtan Bhandar', cuisine: 'Sweets & Snacks', rating: 4.6 },
        { name: 'Ambrai Restaurant', cuisine: 'Multi-cuisine', rating: 4.7 },
      ],
      coordinates: { latitude: 27.0238, longitude: 74.2179 },
    },
    {
      id: '4',
      name: 'Himachal Pradesh',
      image: 'https://images.pexels.com/photos/2531608/pexels-photo-2531608.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Mountain culture with Buddhist influences',
      festivals: 'Kullu Dussehra, Losar, Summer Festival',
      famousPlaces: 'Manali, Shimla, Dharamshala',
      touristAttractions: [
        { name: 'Rohtang Pass', description: 'High mountain pass with snow' },
        { name: 'Mall Road Shimla', description: 'Colonial-era shopping street' },
        { name: 'McLeod Ganj', description: 'Home of Dalai Lama' },
        { name: 'Solang Valley', description: 'Adventure sports destination' },
      ],
      budget: '₹18,000 - ₹35,000 per person for 5 days',
      bestTime: 'March to June, September to December',
      restaurants: [
        { name: 'Johnson\'s Cafe', cuisine: 'Continental', rating: 4.4 },
        { name: 'Cafe 1947', cuisine: 'Italian', rating: 4.5 },
        { name: 'The Himalayan Cafe', cuisine: 'Multi-cuisine', rating: 4.3 },
      ],
      coordinates: { latitude: 31.1048, longitude: 77.1734 },
    },
    {
      id: '5',
      name: 'Tamil Nadu',
      image: 'https://images.pexels.com/photos/3401920/pexels-photo-3401920.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Ancient Dravidian culture with grand temples',
      festivals: 'Pongal, Karthigai Deepam, Mahamaham',
      famousPlaces: 'Mahabalipuram, Madurai, Ooty',
      touristAttractions: [
        { name: 'Meenakshi Temple', description: 'Magnificent temple complex' },
        { name: 'Shore Temple', description: 'UNESCO World Heritage Site' },
        { name: 'Nilgiri Mountain Railway', description: 'Historic toy train ride' },
        { name: 'Marina Beach', description: 'Longest urban beach in India' },
      ],
      budget: '₹15,000 - ₹30,000 per person for 5 days',
      bestTime: 'November to February',
      restaurants: [
        { name: 'Murugan Idli Shop', cuisine: 'South Indian', rating: 4.5 },
        { name: 'Sangeetha Restaurant', cuisine: 'Vegetarian', rating: 4.4 },
        { name: 'Buhari Hotel', cuisine: 'Biryani', rating: 4.3 },
      ],
      coordinates: { latitude: 11.1271, longitude: 78.6569 },
    },
    {
      id: '6',
      name: 'Maharashtra',
      image: 'https://images.pexels.com/photos/739407/pexels-photo-739407.jpeg?auto=compress&cs=tinysrgb&w=800',
      culture: 'Diverse culture blending tradition and modernity',
      festivals: 'Ganesh Chaturthi, Gudi Padwa, Diwali',
      famousPlaces: 'Mumbai, Pune, Ajanta Caves',
      touristAttractions: [
        { name: 'Gateway of India', description: 'Iconic Mumbai monument' },
        { name: 'Ajanta & Ellora Caves', description: 'Ancient rock-cut caves' },
        { name: 'Lonavala', description: 'Hill station near Mumbai' },
        { name: 'Marine Drive', description: 'Scenic coastal promenade' },
      ],
      budget: '₹20,000 - ₹40,000 per person for 5 days',
      bestTime: 'October to February',
      restaurants: [
        { name: 'Britannia & Co.', cuisine: 'Parsi', rating: 4.5 },
        { name: 'Cafe Mondegar', cuisine: 'Continental', rating: 4.3 },
        { name: 'Trishna', cuisine: 'Seafood', rating: 4.6 },
      ],
      coordinates: { latitude: 19.7515, longitude: 75.7139 },
    },
  ];
  
  export const posts = [
    {
      id: '1',
      username: 'traveler_raj',
      userImage: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
      postImage: 'https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg?auto=compress&cs=tinysrgb&w=800',
      caption: 'Sunset at Baga Beach was absolutely magical! 🌅 #GoaDiaries',
      location: 'Baga Beach, Goa',
      likes: 234,
      comments: 45,
      timestamp: '2 hours ago',
      isLiked: false,
    },
    {
      id: '2',
      username: 'wanderlust_priya',
      userImage: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
      postImage: 'https://images.pexels.com/photos/3452356/pexels-photo-3452356.jpeg?auto=compress&cs=tinysrgb&w=800',
      caption: 'Houseboat experience in Kerala backwaters - a dream come true! 🚤',
      location: 'Alleppey, Kerala',
      likes: 567,
      comments: 89,
      timestamp: '5 hours ago',
      isLiked: true,
    },
    {
      id: '3',
      username: 'explorer_amit',
      userImage: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      postImage: 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800',
      caption: 'The royal Amber Fort never fails to amaze! 🏰',
      location: 'Jaipur, Rajasthan',
      likes: 892,
      comments: 156,
      timestamp: '1 day ago',
      isLiked: false,
    },
    {
      id: '4',
      username: 'mountain_girl',
      userImage: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
      postImage: 'https://images.pexels.com/photos/2531608/pexels-photo-2531608.jpeg?auto=compress&cs=tinysrgb&w=800',
      caption: 'Breathing in the fresh Himalayan air at Manali ⛰️',
      location: 'Manali, Himachal Pradesh',
      likes: 445,
      comments: 67,
      timestamp: '2 days ago',
      isLiked: true,
    },
    {
      id: '5',
      username: 'culture_seeker',
      userImage: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=200',
      postImage: 'https://images.pexels.com/photos/3401920/pexels-photo-3401920.jpeg?auto=compress&cs=tinysrgb&w=800',
      caption: 'The intricate architecture of Meenakshi Temple is breathtaking! 🕉️',
      location: 'Madurai, Tamil Nadu',
      likes: 678,
      comments: 92,
      timestamp: '3 days ago',
      isLiked: false,
    },
  ];
  
  export const chatSuggestions = [
    'Plan my trip to Goa',
    'Budget travel to Kerala',
    'Best restaurants in Hyderabad',
    'Top 5 hill stations in India',
    'Weekend getaway from Mumbai',
    'Adventure activities in Manali',
  ];
  
  export const touristSpots = [
    {
      id: '1',
      name: 'Taj Mahal',
      type: 'monument',
      coordinates: { latitude: 27.1751, longitude: 78.0421 },
      description: 'Iconic white marble mausoleum',
    },
    {
      id: '2',
      name: 'Gateway of India',
      type: 'monument',
      coordinates: { latitude: 18.9220, longitude: 72.8347 },
      description: 'Historic arch monument in Mumbai',
    },
    {
      id: '3',
      name: 'Hawa Mahal',
      type: 'monument',
      coordinates: { latitude: 26.9239, longitude: 75.8267 },
      description: 'Palace of Winds in Jaipur',
    },
  ];
  
  export const restaurants = [
    {
      id: '1',
      name: 'Paradise Biryani',
      type: 'restaurant',
      coordinates: { latitude: 17.4399, longitude: 78.3486 },
      cuisine: 'Hyderabadi',
      rating: 4.5,
    },
    {
      id: '2',
      name: 'Karim\'s',
      type: 'restaurant',
      coordinates: { latitude: 28.6508, longitude: 77.2318 },
      cuisine: 'Mughlai',
      rating: 4.6,
    },
    {
      id: '3',
      name: 'MTR',
      type: 'restaurant',
      coordinates: { latitude: 12.9716, longitude: 77.5946 },
      cuisine: 'South Indian',
      rating: 4.7,
    },
  ];
  
  export const userProfile = {
    id: '1',
    username: 'johndoe_traveler',
    name: 'John Doe',
    bio: '✈️ Travel Enthusiast | 📸 Photographer\n🌏 Exploring India one state at a time',
    profileImage: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
    followers: 1234,
    following: 567,
    posts: [
      'https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg?auto=compress&cs=tinysrgb&w=400',
      'https://images.pexels.com/photos/3452356/pexels-photo-3452356.jpeg?auto=compress&cs=tinysrgb&w=400',
      'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=400',
      'https://images.pexels.com/photos/2531608/pexels-photo-2531608.jpeg?auto=compress&cs=tinysrgb&w=400',
      'https://images.pexels.com/photos/3401920/pexels-photo-3401920.jpeg?auto=compress&cs=tinysrgb&w=400',
      'https://images.pexels.com/photos/739407/pexels-photo-739407.jpeg?auto=compress&cs=tinysrgb&w=400',
    ],
    savedPlans: [
      { id: '1', destination: 'Goa Beach Tour', duration: '3 Days', budget: '₹25,000' },
      { id: '2', destination: 'Kerala Backwaters', duration: '5 Days', budget: '₹40,000' },
      { id: '3', destination: 'Rajasthan Heritage', duration: '7 Days', budget: '₹50,000' },
    ],
  };
  